[versions]
accompanistSystemuicontroller = "0.36.0"
agp = "8.13.2"
composePdf = "1.2.0"
composewaveloading = "0.1.4"
datastorePreferences = "1.2.0"
koinBom = "4.1.1"
kotlin = "2.3.0"
ksp = "2.3.4"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
ktor = "3.3.3"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2026.01.00"
lottieComposeVersion = "6.7.1"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.6"
materialKolor = "4.1.0"
appcompat = "1.7.1"
aboutLibraries = '13.2.1'
backdrop = "1.0.4"
capsule = "2.1.2"
voyager = "1.1.0-beta03"


[libraries]
backdrop = { module = "io.github.kyant0:backdrop", version.ref = "backdrop" }
capsule = { module = "io.github.kyant0:capsule", version.ref = "capsule" }

compose-pdf = { module = "dev.zt64:compose-pdf", version.ref = "composePdf" }

koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }


ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }


androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }


material = { group = "androidx.compose.material", name = "material" }


#material = { group = "androidx.compose.material", name = "material" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3-android" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
foundation-android = { group = "androidx.compose.foundation", name = "foundation-android" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }

androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }


appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
android-lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieComposeVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
composewaveloading = { module = "com.github.vitaviva:ComposeWaveLoading", version.ref = "composewaveloading" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }


materialKolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose-core", version.ref = "aboutLibraries" } # Common compose core
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }      # Material 3 UI
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }

voyager-bottom-sheet-navigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-tab-navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }

[bundles]
liquid-glass = ["backdrop","capsule"]
koin = ["koin-android","koin-androidx-compose","koin-core"]
ktor = ["ktor-client-cio","ktor-serialization-kotlinx-json","ktor-client-logging","ktor-client-core","ktor-client-content-negotiation"]
voyager = ["voyager-bottom-sheet-navigator","voyager-koin","voyager-navigator","voyager-screenmodel","voyager-tab-navigator","voyager-transitions"]
compose = ["androidx-material3","androidx-ui-graphics","foundation-android","androidx-compose-material3","androidx-ui"]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }

